### PR TITLE
Android fixes

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by superdump** [comment]
@Rugvip : can you review this please?

**Comment by Rugvip** [comment]
With the changes mentioned in EricssonResearch/openwebrtc-android-sdk#19 to/FromJsep would change, otherwise 👍

**Comment by sdroege** [comment]
This should support both, and actually support the old-style SDP correctly (it probably didn't work before if I understand it correctly).

The problem here was that in NativeCall from the very beginning only supported the non-SDP session description. Then in e9d7cc533e35128bd37a71976a122c8b3108b5c4 the local implementation of that was ripped out in favour of the SDK. Now the SDK only supported the SDP session description, and for some reason the SDP session description was wrapped in yet another object into an "sdp" field. It doesn't look like that is how it was supposed to be done (I don't think this ever worked with anything but NativeCall itself) and was probably a copy&paste mistake from the candidate (where you have to wrap it in another object).

**Comment by sdroege** [comment]
@Rugvip can you review this one here too? Good to go together with the other one?

**Comment by Rugvip** [comment]
Yup, the wrapping in an extra "sdp" property was clearly wrong, good catch.

:+1:

**Comment by sdroege** [comment]
You have to merge it then, I don't have access to this specific repository apparently :)

**Pull request closed without merging**
