### PR TITLE
tweak signaling to support both JSON and SDP messages

### PR DESCRIPTION
**Pull request by alessandrod**

### CODE REVIEW

**Comment by stefhak** [comment]
great work - now it works when I test locally between browsers. Can I be notified somehow when this is live on demo.openwebrtc.org so I can test?

**Comment by stefanalund** [comment]
@superdump can you update the live server?

**Comment by stefhak** [comment]
I tested yesterday, and it seemed the live server was already updated.

**Comment by superdump** [comment]
I have better access to the server now so it will be kept in sync with master.

**Pull request closed without merging**
